import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Contact",
  description: "Generated by create next app2121",
};

const ContactPage = () => {
  return (
    <div>ContactPage</div>
  )
}

export default ContactPage